### ISSUE TITLE
How to align the arrow icon to the left of the text?

### ISSUE THREAD

**Issue by SaathwikS** [dooboolab/react-native-drop-down-item#35]

**Comment by hyochan** [comment]
Hi. Thank you for the issue. The package has been removed to [@dooboo-ui/native-switch-toggle](https://www.npmjs.com/package/@dooboo-ui/native-switch-toggle).

If you still need an assistance, please write up an issue in [dooboo-ui/native](https://github.com/dooboolab/dooboo-ui-native).
